src/Entity/ProductDetail.php
<?php

namespace App\Entity;

use App\Repository\ProductDetailRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductDetailRepository::class)]
class ProductDetail
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'productDetails')]
    private $CategoryId;

    #[ORM\Column(type: 'string', length: 255)]
    private $Quantity;

    #[ORM\Column(type: 'text')]
    private $Description;

    #[ORM\Column(type: 'string', length: 50)]
    private $Brand;

    #[ORM\OneToMany(mappedBy: 'ProductDetailId', targetEntity: Product::class)]
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryId(): ?Category
    {
        return $this->CategoryId;
    }

    public function setCategoryId(?Category $CategoryId): self
    {
        $this->CategoryId = $CategoryId;

        return $this;
    }

    public function getQuantity(): ?string
    {
        return $this->Quantity;
    }

    public function setQuantity(string $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->Brand;
    }

    public function setBrand(string $Brand): self
    {
        $this->Brand = $Brand;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setProductDetailId($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getProductDetailId() === $this) {
                $product->setProductDetailId(null);
            }
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{

    private $em;
    private $categoryRepository;
    private $productRepository;

    public function __construct(CategoryRepository $categoryRepository, ProductRepository $productRepository, EntityManagerInterface $em)
    {
        $this->categoryRepository = $categoryRepository;
        $this->productRepository = $productRepository;
        $this->em = $em;
    }


    #[Route('/home', name: 'app_home')]
    public function index(): Response
    {
        return $this->render('home/homePage.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/about', name: 'app_about')]
    public function aboutAction(): Response
    {
        return $this->render('home/homePage.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/list/product', name: 'app_list_product')]
    public function productAction(): Response
    {
        $product = $this->productRepository->findAll();
        return $this->render('home/listProduct.html.twig', [
            'product_list' => $product,
        ]);
    }

    #[Route('/details/product/{id}', name: 'app_details_product')]
    public function detailsAction($id): Response
    {
        $getOne = $this -> productRepository -> find($id);
        return $this->render('home/detailProduct.html.twig', [
            'details' => $getOne,
        ]);
    }

    #[Route('/contact', name: 'app_contact')]
    public function contactAction(): Response
    {
        return $this->render('home/homePage.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

templates/home/detailProduct.html.twig
 {% extends "index.html.twig" %}

{% block body %}
    
    <div class="our_section layout_padding">
      <div class="container">
         <div class="row">
            <div class="col-sm-12">
               <h1 class="our_text"><strong>{{details.productName}}</strong></h1>
               <p class="about_lorem">{{details.description}}</p>
            </div>
         </div>
      </div>
      <div class="our_section_2">
         <div class="our_main">
            <div id="my_slider" class="carousel slide" data-ride="carousel">
               <div class="carousel-inner">
               <div class="carousel-item active">
                  <img class="d-block w-100" src="{{details.image}}" alt="First slide">
               </div>
            
            </div>
               <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                 <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                 <span class="sr-only">Previous</span>
               </a>
               <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                 <span class="carousel-control-next-icon" aria-hidden="true"></span>
                 <span class="sr-only">Next</span>
               </a>
            </div>
         <h2>Price: {{details.price}}$</h2>
         <h2>Quantity: {{details.quantity}}</h2>
          </div>

          <button class="seemore_bt" href="#">Add to cart</button>
      </div>
   </div>

{% endblock %}

templates/home/homePage.html.twig
 {% extends "index.html.twig" %}

 {% block body %}

  <!-- about section start -->
   <div class="container-fluid">
   <div class="about_section">
      <div class="container">
         <div class="about_img"><img src="{{asset('build/images/about-img1.png')}}" style="max-width: 100%;"></div>
         <h2 class="about_text"><strong>About <span style="color: #000;">Us</span></strong></h2>
         <div class="about_middle">
            <p class="about_lorem">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it </p>
         </div>
         <div class="red_bt">
            <button class="read_more">Read More</button>
         </div>
      </div>
   </div>
   </div>
   <!-- about section end -->
   <!-- our section start -->
   <div class="our_section">
      <div class="container">
         <div class="row">
            <div class="col-sm-12">
               <h1 class="our_text"><strong>Our <span style="color: #000;">Cycles</span></strong></h1>
               <p class="about_lorem">t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum</p>
            </div>
         </div>
      </div>
      <div class="our_section_2">
         <div class="our_main">
            <div id="my_slider" class="carousel slide" data-ride="carousel">
               <div class="carousel-inner">
               <div class="carousel-item active">
                  <img class="d-block w-100" src="{{asset('buid/images/our-img-1.png')}}" alt="First slide">
               </div>
               <div class="carousel-item">
                  <img class="d-block w-100" src="{{asset('build/images/our-img-1.png')}}" alt="Second slide">
               </div>
               <div class="carousel-item">
                 <img class="d-block w-100" src="{{asset('build/images/our-img-1.png')}}" alt="Third slide">
               </div>
            </div>
               <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                 <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                 <span class="sr-only">Previous</span>
               </a>
               <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                 <span class="carousel-control-next-icon" aria-hidden="true"></span>
                 <span class="sr-only">Next</span>
               </a>
            </div>
          </div>
          <button class="seemore_bt">See More</button>
      </div>
   </div>
   <div class="contact_section layout_padding">
      <div class="container">
         <h1 class="contact_text"><strong>Contact Us</strong></h1>
      </div>
            <div class="contact_main">
               <div class="enput_section">
                  <div class="email_box">
                    <div class="input_main">
                       <div class="container">
                          <form action="/action_page.php">
                            <div class="form-group">
                              <input type="text" class="email-bt" placeholder="Name" name="Name">
                            </div>
                            <div class="form-group">
                              <input type="text" class="email-bt" placeholder="Email" name="Name">
                            </div>
                            <div class="form-group">
                              <input type="text" class="email-bt" placeholder="Phone number" name="Email">
                            </div>
                            
                            <div class="form-group">
                                <textarea class="massage-bt" placeholder="Massage" rows="5" id="comment" name="Massage"></textarea>
                            </div>
                          </form>   
                       </div> 
                       <div class="send_btn">
                        <button type="button" class="main_bt"><a href="#">Send</a></button>
                       </div>                   
                    </div>
                 </div>
               </div>
            </div>
   </div>
   <!-- our section end -->
   <!-- Testimonial section start -->
   <div class="testimonial_section layout_padding">
      <div class="container">
         <h1 class="contact_text"><strong>Testimonial</strong></h1>
         <p class="dolore_text">consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna  </p>
         <div class="images_3"><img src="{{asset('build/images/img-3.png')}}"></div>
         <h2 class="rooty_text">Rooty</h2>
         <p class="ice_text">(lcc)</p>
         <div><img src="images/left-quote.png"></div>
         <p class="dolore_text">consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore  , quis nostrud exercitation </p>
         <div class="right_quote"><img src="{{asset('build/images/right-quote.png}')}}"></div>
      </div> 
   </div>


 {% endblock %}

{% block headerBanner %}
<div class="banner_section layout_padding">
      <div class="container">
      <section >
         <div id="main_slider" class="section carousel slide banner-main" data-ride="carousel">
            <ol class="carousel-indicators">
               <li data-target="#main_slider" data-slide-to="0" class="active"></li>
               <li data-target="#main_slider" data-slide-to="1"></li>
               <li data-target="#main_slider" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <div class="row marginii">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                           <div class="carousel-sporrt_text ">
                              <h1 class="sport_text"><strong>Sports<br><span style="color: #fff;">Cycle</span></strong></h1>
                              <p class="lorem_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content</p>
                              <button class="boynow_bt">Boy Now</button>
                              <button class="contact_bt">Contact Us</button>
                           </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                           <div class="img-box">
                              <figure><img src="images/img-1.png" style="max-width: 100%;"/></figure>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <div class="container">
                     <div class="row marginii">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                           <div class="carousel-sporrt_text ">
                              <h1 class="sport_text"><strong>Sports<br><span style="color: #fff;">Cycle</span></strong></h1>
                              <p class="lorem_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content</p>
                              <button class="boynow_bt">Boy Now</button>
                              <button class="contact_bt">Contact Us</button>
                           </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                           <div class="img-box">
                              <figure><img src="images/img-1.png" style="max-width: 100%;"/></figure>
                           </div>
                        </div>
                     </div>
                  </div>
                  </div>
               </div>
               <div class="carousel-item">
                  <div class="container">
                     <div class="row marginii">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                           <div class="carousel-sporrt_text ">
                              <h1 class="sport_text"><strong>Sports<br><span style="color: #fff;">Cycle</span></strong></h1>
                              <p class="lorem_text">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content</p>
                              <button class="boynow_bt">Boy Now</button>
                              <button class="contact_bt">Contact Us</button>
                           </div>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                           <div class="img-box">
                              <figure><img src="images/img-1.png" style="max-width: 100%;"/></figure>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      </div>
      </div>
{% endblock %}

templates/home/listProduct.html.twig
 {% extends "index.html.twig" %}



 {% block body %}

<div class="container py-5">
    <div class="row text-center text-white mb-5">
        <div class="col-lg-7 mx-auto">
            <h1 class="display-4">Product List</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <!-- List group-->
            <ul class="list-group shadow">
                <!-- list group item-->
                {% for row in product_list %}
                  <li  class="list-group-item">
                    <!-- Custom content-->
                    <a href="{{path('app_details_product',{'id':row.id})}}" class="media align-items-lg-center flex-column flex-lg-row p-3">
                        <div class="media-body order-2 order-lg-1">
                            <h5 class="mt-0 font-weight-bold mb-2">{{row.productName}}</h5>
                            <p class="font-italic text-muted mb-0 small">{{row.description}}</p>
                            <div class="d-flex align-items-center justify-content-between mt-1">
                                <h6 class="font-weight-bold my-2">{{row.price}} $</h6>
                                <ul class="list-inline small">
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                                    <li class="list-inline-item m-0"><i class="fa fa-star-o text-gray"></i></li>
                                </ul>
                            </div>
                        </div><img src="{{row.image}}" alt="Generic placeholder image" width="200" class="ml-lg-5 order-1 order-lg-2">
                    </a> <!-- End -->
                </li>  
                {% endfor %}
              
            </ul> <!-- End -->
        </div>
    </div>
</div>

 {% endblock %}